PASS =		ex1

HDRS =		ex1.h
OBJS =		ex1.o suif_pass.o
MAIN_OBJ =	suif_main.o
CPPS =		$(OBJS:.o=.cpp) $(MAIN_OBJ:.o=.cpp)

NWHDRS =	$(HDRS)
NWCPPS =	ex1.cpp

LIBS =		-lmachine

include $(MACHSUIFHOME)/Makefile.common
