#SUIF_INTERNAL = defined
OBJ_FILES =  type_builder.o
SRCS = type_builder.cpp
HEADERS = type_builder.h type_builder_forwarders.h

TARGET_LIB = typebuilder

LIBS += -lsuifnodes -lsuifkernel -liokernel -lbasicnodes -lcommon

include $(NCIHOME)/Makefile.std
