OBJ_FILES =  create_suif_hello_world.o

SRCS = create_suif_hello_world.cpp

PROGRAM = create_suif_hello_world
LIBS += -liokernel -lsuifkernel -lsuifnodes -lbasicnodes -lcommon \
	-ltypebuilder

include $(NCIHOME)/Makefile.std

