PASS =		ex3

HDRS =		ex3.h
OBJS =		ex3.o suif_pass.o
MAIN_OBJ =	suif_main.o
CPPS =		$(OBJS:.o=.cpp) $(MAIN_OBJ:.o=.cpp)

NWHDRS =	$(HDRS)
NWCPPS =	ex3.cpp

LIBS =		-lmachine

include $(MACHSUIFHOME)/Makefile.common
