# The primary interfaces is tos.h

SRCS = string_enum.cpp

HEADERS = string_enum.h

OBJ_FILES = string_enum.o

TARGET_LIB = string_enum

EXTRA_CXXFLAGS += -DINLINE_ALL_TEMPLATES
LIBS += -lcommon

include $(NCIHOME)/Makefile.std
