#!/bin/sh



# useful variables 
ROCCC_HOME=$PWD/..
NUSUIF_DIR=$PWD/NuSuif
SUIF2_DIR=$NUSUIF_DIR/suif2
MACHSUIF_DIR=$NUSUIF_DIR/machsuif

MAKEFILE_STD=$SUIF2_DIR/Makefile.std
MAKEFILE_PROTO=$SUIF2_DIR/Makefile.proto
NCISETUP_SH=$SUIF2_DIR/nci_setup.sh
FORCE_WRITE=""

USESUIF_SH=$ROCCC_HOME/use_suif.sh
CURRENT_DIR=$PWD

get_compiler_name()
    {
       cname=''
       case x$1 in
	x*gcc | x*g++)
          val=`$1 -v 2>&1 | grep egcs | wc -l`
	  if [ $val -gt 0 ]
	     then cname=egcs
          else
	     cname=gcc
	  fi  ;;
        *CC)
           if [ $ARCH = "SunOS" ] ; then cname=sun_procompiler ;
           elif [ $ARCH = "IRIX" ] ; then cname=sgi_c++ ;
	   fi ;;
	*) ;;
	esac
    }

set_arch()
    {
    ARCH=$1
    }

set_pwd()
    {
    PWD=`pwd`
    }

emitmake()
    {
    echo "ifeq (,\$(NCI_${1}))" >> $MAKEFILE_STD
    echo $1 = $2 >> $MAKEFILE_STD
    echo else >> $MAKEFILE_STD
    echo $1 = "\$(NCI_${1})" >> $MAKEFILE_STD
    echo endif >> $MAKEFILE_STD
    echo >> $MAKEFILE_STD
    }

emit()
    {
    echo "ifeq (,\$($1))" >> $MAKEFILE_STD
    echo $1 = $2 >> $MAKEFILE_STD
    echo endif >> $MAKEFILE_STD
    echo >> $MAKEFILE_STD
    }

emitgc()
    {
    echo "ifeq (,\$(GC_DIRS_SET))" >> $MAKEFILE_STD
    echo "GC_DIRS_SET = 1" >> $MAKEFILE_STD
    echo "GC_INCLDIRS = ${NCI_GC_INCLDIRS}" >> $MAKEFILE_STD
    echo "GC_LIBDIRS = ${NCI_GC_LIBDIRS}" >> $MAKEFILE_STD
    echo endif >> $MAKEFILE_STD

    echo "ifeq (,\$(OMEGA_SET))" >> $MAKEFILE_STD
    echo "OMEGA_SET = 1" >> $MAKEFILE_STD
    echo "OMEGA_INCLDIRS = ${NCI_OMEGA_INCLDIRS}" >> $MAKEFILE_STD
    echo "OMEGA_LIBDIRS = ${NCI_OMEGA_LIBDIRS}" >> $MAKEFILE_STD
    echo endif >> $MAKEFILE_STD

    echo "ifeq (,\$(TCL_SET))" >> $MAKEFILE_STD
    echo "TCL_INCLDIRS = ${NCI_TCL_INCLDIRS}" >> $MAKEFILE_STD
    echo "TCL_LIBDIRS = ${NCI_TCL_LIBDIRS}" >> $MAKEFILE_STD
    echo endif >> $MAKEFILE_STD

    echo >> $MAKEFILE_STD
    }

emitsh()
    {
    echo "$1=$2; export $1" >> $NCISETUP_SH
    }

emitcsh()
    {
    echo setenv $1 $2 >> nci_setup.csh
    }


emit_usesuif()
    {
        if [ -f $USESUIF_SH ]; then 
            if [ -z $FORCE_WRITE ]; then 
                echo "$USESUIF_SH already exists.  Use --FORCE option to overwrite"
                exit 1
            else
                echo "" > $USESUIF_SH
            fi
        fi

        echo "Writing $USESUIF_SH..."

        echo '#!/bin/sh'                                                               >> $USESUIF_SH
        echo '# This file sets up environment variables which are necessary for using' >> $USESUIF_SH
        echo '# any of the suif programs.'                                             >> $USESUIF_SH
        echo '#'                                                                       >> $USESUIF_SH
        echo '#'                                                                       >> $USESUIF_SH
        echo '# Where the Suif2 & MachineSuif Variables are located'                   >> $USESUIF_SH
        echo '#'                                                                       >> $USESUIF_SH
        echo "export ROCCC_HOME=$ROCCC_HOME"                                           >> $USESUIF_SH
        echo "source $NCISETUP_SH"                                                     >> $USESUIF_SH
        echo '#'                                                                       >> $USESUIF_SH
        echo '#'                                                                       >> $USESUIF_SH

    }



get_first()
    {
    the_path=$1
    }

mywhich() {
   type -a $1 | head -1 | awk '{print $3}'
 }

find()
    {
    command=$1
    shift
    preference=`eval echo \\$NCI_$command`
    for i in $preference $*
    do
        case x$i in
	  x/*) the_path=$i;;  # absolute path
	  *) get_first `which $i 2>/dev/null`;;
        esac
	if [ X"$the_path" != X"" ]; then
	    if [ -x $the_path ]; then
	            emitmake $command $the_path
	    command_name=$i
	    return
	    fi
    	fi
	done
    echo WARNING: Could not find $command. Installing without explicit path
    emitmake $command $command
    command_name=$command
    return
    }

findinclude()
    {
    envname=$1
    file=$2
    shift
    shift
    for i in $*
    do
   	if [ -r $i/$file ]; then
	    emit $envname $i
	    return
	fi
    done
    echo cannot find file $file
    }

help_usage()
    {
    echo "Usage: $0 [--with-CC_CXX_PATH=PATH_TO_GCC_4.0.2_BIN_DIR] "
#    echo "Usage: $0 [--with-CXX=compiler] [--with-CC=cc_compiler] "
#    echo "       [--with-CXXPARSER=compiler]"
#    echo ""
# redundant, set --with-CXXLINK equal to output of --with-CXX
#    echo "       [--with-CXXLINK=compiler] [--with-LOCAL_BASE] [--help]"
#    echo "       [--with-TCL_LIBDIRS=libs] [--with-LOCAL_BASE] [--help]"
    echo "    To find the default compiler, we search for"
    echo "    gcc g++ in the current path"
#    echo "    eg++ g++ CC and cc in the current path"
#    echo "    to override this either set the environment"
#    echo "    variables NCI_CXX and NCI_CC NCI_CXXLINK or use the"
#    echo "    --with-CXX= , --with-CC= "
#    echo "    --with-CXXLINK=   command line options"
#    echo "    --with-TCL_LIBDIRS=   -Ldirs and -llib needed to link TCL"
#    echo " To specify the garbage collector path"
#    echo "    --with-DOT='dot' "
#    echo "    --with-GV='gv' "
#    echo " To specify the garbage collector path"
#    echo "    --with-GC_LIBDIRS='-Lpath -lgc'"
#    echo "    --with-GC_INCLDIRS=-Ipath"
#    echo " To specify the path for the Omega library"
#    echo "    --with-OMEGA_LIBDIRS='-Lpath -lgc' "
#    echo "    --with-OMEGA_INCLDIRS=-Ipath"
    echo ""
    echo " This program will build the files"
#    echo "    Makefile.std, nci_setup.csh and $NCISETUP_SH"
    echo "    Makefile.std and $NCISETUP_SH"
    echo "    NOTE: if they already exists then use the --FORCE option to overwrite "
#    echo " If you specify --with-LOCAL_BASE, local solib and bin directories will be "
#    echo " added to the LD_LIBRARY_PATH and PATH."
    exit 2
    }

NCI_GC_LIBDIRS=-lgc
NCI_GC_INCLDIRS=

NCI_OMEGA_LIBDIRS=-lomega
NCI_OMEGA_INCLDIRS=

#NCI_TCL_LIBDIRS="-L/usr/openwin/lib -L/usr/X11/lib -L/usr/X11R6/lib -ltcl8.0"
#NCI_TCL_INCLDIRS="-I/usr/local/ultra/include -I/usr/openwin/include"
NCI_TCL_INCLDIRS=
NCI_TCL_LIBDIRS="-ltcl8.0"

#NCI_DOT=dot
#NCI_GV=gv
while [ $?1 ]; do
   case $1 in
     --with-CC_CXX_PATH=*)
        NCI_CC=`echo $1|sed 's/^--with-CC_CXX_PATH=//'`gcc;  
        NCI_CXX=`echo $1|sed 's/^--with-CC_CXX_PATH=//'`g++;  
        NCI_CXXPARSER=`echo $1|sed 's/^--with-CC_CXX_PATH=//'`g++;  
        NCI_CXXLINK=`echo $1|sed 's/^--with-CC_CXX_PATH=//'`g++;  
        shift;;

#     --with-CXX=*) 
#        NCI_CXX=`echo $1|sed 's/^--with-CXX=//'`;  
#        # set if not already defined, because can be same as cxx 
#        if [ x"$NCI_CXXLINK"==x"" ]; then 
#            NCI_CXXLINK=`echo $1|sed 's/^--with-CXX=//'`;  
#        fi
#        # set if not already defined, because can be same as cxx 
#        if [ x"$NCI_CXXPARSER"==x"" ]; then 
#            NCI_CXXPARSER=`echo $1|sed 's/^--with-CXX=//'`;  
#        fi
#        shift;;
#     --with-CC=*) NCI_CC=`echo $1|sed 's/^--with-CC=//'`; shift;;
#     --with-CXXLINK=*) NCI_CXXLINK=`echo $1|sed 's/^--with-CXXLINK=//'`; shift;;
#     --with-CXXPARSER=*) NCI_CXXPARSER=`echo $1|sed 's/^--with-CXXPARSER=//'`; shift;;
#     --with-GC_LIBDIRS=*) NCI_GC_LIBDIRS=`echo $1|sed 's/^--with-GC_LIBDIRS=//'`; shift;;
#     --with-GC_INCLDIRS=*) NCI_GC_INCLDIRS=`echo $1|sed 's/^--with-GC_INCLDIRS=//'`; shift;;
#     --with-OMEGA_LIBDIRS=*) NCI_OMEGA_LIBDIRS=`echo $1|sed 's/^--with-OMEGA_LIBDIRS=//'`; shift;;
#     --with-OMEGA_INCLDIRS=*) NCI_OMEGA_INCLDIRS=`echo $1|sed 's/^--with-OMEGA_INCLDIRS=//'`; shift;;
#     --with-TCL_LIBDIRS=*) NCI_TCL_LIBDIRS=`echo $1|sed 's/^--with-TCL_LIBDIRS=//'`; shift;;
#     --with-TCL_INCLDIRS=*) NCI_TCL_INCLDIRS=`echo $1|sed 's/^--with-TCL_INCLDIRS=//'`; shift;;
#     --with-DOT=*) NCI_DOT=`echo $1|sed 's/^--with-DOT=//'`; shift;;
#     --with-GV=*) NCI_GV=`echo $1|sed 's/^--with-GV=//'`; shift;;
#     --with-LOCAL_BASE) LOCAL_BIN='$LOCAL_BASE/bin'; LOCAL_LD_LIB='$LOCAL_BASE/solib'; shift;;
     --FORCE) FORCE_WRITE='1'; shift;;
     --help) help_usage;;
     -*) echo "unknown option $1"; help_usage;;
     *) break;;
   esac
done

if [ ! -f $MAKEFILE_PROTO ]; then
	echo $MAKEFILE_PROTO not found in NuSuif directory.
	echo Please make sure to run install in the root of NCI tree.
	exit 1
	fi

if [ -f $MAKEFILE_STD ]; then 
    if [ -z $FORCE_WRITE ]; then
        echo $MAKEFILE_STD exists. Use --FORCE option to overwrite
        exit 2
    else
        echo "" > $MAKEFILE_STD
    fi
fi

echo  Creating $MAKEFILE_STD

echo \# The following settings are created by the install script >> $MAKEFILE_STD
echo \# Edit them to taste >> $MAKEFILE_STD
echo >> $MAKEFILE_STD

set_arch `uname -a`

set_pwd

emit ARCH $ARCH

emit NCIHOME $SUIF2_DIR

emit MACHSUIFHOME $MACHSUIF_DIR

find MAKE gmake make

find AWK gawk nawk awk

find CXXLINK eg++ g++ CC cc

find CXXPARSER eg++ g++ CC cc

find CXX eg++ g++ CC cc

#findinclude X11_INCLUDE X11/Xlib.h /usr/X*/include /usr/include /usr/openwin/share/include

#cmpl_name=get_compiler_name $command_name
get_compiler_name $command_name

emit COMPILER_NAME $cname

find CC egcc gcc cc

find AS as

#find YACC yacc
find BISON bison

find LEX lex

#find DOT dot

#find GV gv

if [ -n "$USE_ZEPHYR" ]
then
    find SML_CM sml-cm
    find SML sml
    fi

find PERL perl

emitgc

echo \# end of install generated settings >> $MAKEFILE_STD
echo \include \$\(NCIHOME\)/Makefile.proto >> $MAKEFILE_STD

if [ -f $NCISETUP_SH ]; then
    if [ -z $FORCE_WRITE ]; then 
        echo $NCISETUP_SH already exists.  Use --FORCE option to overwrite.
        exit 3
    else
        echo "" > $NCISETUP_SH
    fi
fi	
echo Creating $NCISETUP_SH

    emitsh NCIHOME $SUIF2_DIR
    emitsh MACHSUIFHOME $MACHSUIF_DIR
    emitsh ARCH $ARCH
    emitsh LD_LIBRARY_PATH $LOCAL_LD_LIB:\$ROCCC_HOME/solib:\$LD_LIBRARY_PATH
    emitsh PATH $LOCAL_BIN:\$ROCCC_HOME/bin:\$PATH


emit_usesuif

echo ""
echo ""
echo "source this file to setup your environment variables: $USESUIF_SH "
echo ""

