PACKAGES =  common  tools  basesuif  utils  cfeutils extratypes #basepasses 

PACKAGES += `grep -v '^\#' extra_suif_packages`

ifneq (,$(BUILDDOCS))
PACKAGES += doc
endif

include $(NCIHOME)/Makefile.std






