#SCRIPTS =	do_lower do_print do_printsuif
BINSCRIPTS =	do_lower do_print do_printsuif

BUILDPACKAGE_RULE = define

buildpackage: install_scripts

all: install_scripts

include $(NCIHOME)/Makefile.std
