##===- lib/Transforms/Makefile -----------------------------*- Makefile -*-===##
# 
#                     The LLVM Compiler Infrastructure
#
# This file is distributed under the University of Illinois Open Source
# License. See LICENSE.TXT for details.
# 
##===----------------------------------------------------------------------===##

LEVEL = ../..
#PARALLEL_DIRS = Utils IPO Scalar PipelinePass VHDLOutputPass RocccCFGtoDFG IntrinsicPass DatapathPrinter
PARALLEL_DIRS = Utils Instrumentation Scalar IPO PipelinePass VHDLOutputPass RocccCFGtoDFG IntrinsicPass DatapathPrinter

include $(LEVEL)/Makefile.common

