PASS =		exp_alpha

OBJS =		exp_alpha.o suif_pass.o
MAIN_OBJ =	suif_main.o
CPPS =		$(OBJS:.o=.cpp) $(MAIN_OBJ:.o=.cpp)
HDRS =		exp_alpha.h suif_pass.h

LIBS =		-lmachine -lcfg -lalpha

include $(MACHSUIFHOME)/Makefile.common
