#SUIF_INTERNAL = defined
OBJ_FILES = suiflocation.o \
location_modules.o

SRCS = location_modules.cpp suiflocation.cpp

HEADERS = location_modules.h

TARGET_LIB = suiflocation
LIBS += $(DYNAMIC_LINKING_LIBRARY) -lcommon -liokernel -lsuifkernel -lbasicnodes -lsuifnodes

include $(NCIHOME)/Makefile.std






