SUIF_INTERNAL = defined

SRCS = MacroObjAdapterBase.cpp

HEADERS = MacroObjAdapterBase.h

OBJ_FILES = MacroObjAdapterBase.o 

LIBS += -lcommon -lsmgn -liokernel -lsuifkernel -lbasicnodes -lsuifnodes

TARGET_LIB = macro_suifobj_adapter

include $(NCIHOME)/Makefile.std


