OBJ_FILES =  suifprinter.o cprint_style.o id_printer.o \
	mc_style.o

HEADERS = suifprinter.h cprint_style.h \
	mc_style.h
SRCS = suifprinter.cpp cprint_style.cpp id_printer.cpp \
	mc_style.cpp

TARGET_LIB = suifprinter
LIBS += -lsuifkernel -liokernel -lcommon -lbasicnodes -lsuifnodes 

include $(NCIHOME)/Makefile.std

