BINSCRIPTS = compile_c2hicirrf2vhdl.py 
BINSCRIPTS += compile_c2hicirrf.py 
BINSCRIPTS += compile_hicirrf2vhdl.py 
BINSCRIPTS += compile_vhdl2fpga.py 
BINSCRIPTS += compile_test_dir.py 
BINSCRIPTS += roccc_python_lib.py

BUILDPACKAGE_RULE = define

buildpackage: install_scripts

all: install_scripts

include $(NCIHOME)/Makefile.std
