OBJ_FILES =  cloner.o

SRCS = cloner.cpp

HEADERS = cloner.h

TARGET_LIB = suifcloning
INCLDIRS += 
LIBS += -lsuifkernel -liokernel -lcommon -lbasicnodes -lsuifnodes

include $(NCIHOME)/Makefile.std

