SUIF_INTERNAL = defined
HEADERS = cfe_dismantle.h cexpr_utils.h cfenode_builder.h

SRCS = cfe_dismantle.cpp cexpr_utils.cpp cfenode_builder.cpp

OBJ_FILES = cfe_dismantle.o cexpr_utils.o cfenode_builder.o

LIBS += -lsuifnodes -lsuifkernel -liokernel -lbasicnodes -lcommon \
	-ltypebuilder -lutils -lcfenodes

TARGET_LIB = cfeutils

include $(NCIHOME)/Makefile.std


