SUIF_INTERNAL = defined
PACKAGES = iokernel suifkernel basicnodes suifnodes cfenodes 
PACKAGES += suiflocation
PACKAGES += suifcloning typebuilder suifpasses driver testpasses suifprinter 
PACKAGES += macro_suifobj_adapter s2c samples

include $(NCIHOME)/Makefile.std

