SUIF_INTERNAL = defined
OBJ_FILES =  
MAIN_OBJ =  suifdriver.o

PROGRAM = suifdriver
LIBS += -lsuifpasses -lbasicnodes -lsuifnodes -lsuifkernel \
	-liokernel -lcommon $(DYNAMIC_LINKING_LIBRARY)

SRCS = suifdriver.cpp

include $(NCIHOME)/Makefile.std
